# Generated by Django 3.2.4 on 2021-06-08 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigMarketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apis', models.CharField(max_length=200)),
                ('keys', models.CharField(max_length=200)),
                ('endspoints', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('config_marketplace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='marketplaceapp.configmarketplace')),
            ],
        ),
    ]
