# Generated by Django 3.2.4 on 2021-06-08 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaceapp', '0002_alter_marketplace_config_marketplace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configmarketplace',
            old_name='endspoints',
            new_name='endpoints',
        ),
    ]
